Repository MyEvilpumpkin/ArticleProcessing, pull requests merged in 2023-11, with the labels that each got.

#3 Removed unused model (sensitive_topics_definition)
  README.md
  article_processing/__init__.py
  article_processing/sensitive_topics_definition.py
  article_processing/sensitive_topics_ids.json
  test.py
Labels: enhancement

#5 Add streamlit
  requirements.txt
  streamlit_app.py
Labels: enhancement

#6 Genre to lowercase
  article_processing/genre_definition.py
  debugger.py
Labels: enhancement

#9 Revert "unittest to pytest"
  .gitignore
  __pycache__/test_1.cpython-310-pytest-7.4.3.pyc
  article_processing/__pycache__/__init__.cpython-310.pyc
  article_processing/__pycache__/genre_definition.cpython-310.pyc
  article_processing/__pycache__/summarization.cpython-310.pyc
  requirements.txt
  tests/test_genres_model.py
Labels: bug, enhancement

#8 Web apps generalization
  article_processing/__init__.py
  streamlit_app.py
  web_app.py
Labels: enhancement

#11 Unittest to pytest
  tests/test_genres_model.py
Labels: enhancement

#12 Common fixes
  requirements.txt
  test_sample.py
  tests/__init__.py
  tests/test_genres_model.py
Labels: enhancement

#22 Add Streamlit docs
  README.md
Labels: documentation, enhancement

#23 Dockers improvement
  Dockerfile
  docker-compose.yml
Labels: enhancement

#26 Repo cleaning
  .devcontainer/devcontainer.json
  .gitignore
  article_processing/__pycache__/__init__.cpython-310.pyc
  article_processing/__pycache__/genre_definition.cpython-310.pyc
  article_processing/__pycache__/language_detection.cpython-310.pyc
  debugger.py
  requirements.txt
  tests/__pycache__/__init__.cpython-310.pyc
  tests/__pycache__/test_genres_model.cpython-310-pytest-7.4.3.pyc
  tests/__pycache__/test_lang_detection_model.cpython-310-pytest-7.4.3.pyc
Labels: enhancement

#30 API tests
  article_processing/__init__.py
  requirements.txt
  test_articles/здоровье_2.txt
  test_articles/экономика_2.txt
  tests/__init__.py
  tests/test_genre_definition.py
  tests/test_web_app.py
  web_app.py
Labels: enhancement

#32 Models usage update
  README.md
  article_processing/__init__.py
  article_processing/genre_definition.py
  article_processing/language_detection.py
  article_processing/summarization.py
  debugger.py
  libs/__init__.py
  libs/file_reader.py
  libs/pipeline_loader.py
  tests/test_genre_definition.py
  tests/test_lang_detection_model.py
  tests/test_web_app.py
Labels: enhancement
